---
ID: "ed44be2f-342b-4ba1-9528-144e191a15b7"
Parent: "eab542cb-e55d-4287-b1de-efb8b638739b"
Template: "0f592683-a8ee-4e11-b8d7-68a99b57b208"
Path: /sitecore/templates/Branches/Project/HackathonSite/Homepage/$name/Configuration/Header Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200229T182433Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
